"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*j$+87@wzila3!jn!#*_g$z0cw3lha99@y2%x49llut-0mbnbs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'import_export',

    # Daftarkan aplikasi evaluasi Anda di sini
    'evaluasi',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'evaluasi.context_processors.daftar_indeks_global',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Database
# Diubah untuk koneksi ke PostgreSQL di dalam Docker container
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'pemdi_db',
        'USER': 'pemdi_user',
        'PASSWORD': 'KerjaIbadah123',
        'HOST': 'db',  # Ini menyambung ke nama service 'db' di docker-compose.yml
        'PORT': '5432',
    }
}

# Pastikan juga ALLOWED_HOSTS mengizinkan akses lokal
ALLOWED_HOSTS = ['*']

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'id'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Jakarta'

# PASTIKAN INI TRUE: Agar Django mendukung zona waktu secara global
USE_I18N = True

# PASTIKAN INI TRUE: Agar Django menyimpan data ke DB dalam format UTC, 
# tetapi otomatis mengonversinya ke Asia/Jakarta saat ditampilkan di template/views
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Folder tempat mencari static saat development
STATIC_URL = '/static/'

# Folder TUJUAN akhir tempat mengumpulkan semua file static untuk Nginx
# Pastikan mengarah ke folder 'static' di dalam direktori 'app' Anda
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Tambahkan baris ini jika belum ada (opsional, untuk memperkuat pencarian folder static)
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# PENGATURAN KEDALUWARSA SESI (SESSION TIMEOUT)
# ==============================================================================

# Sesi otomatis habis jika browser ditutup oleh user
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Durasi masa aktif sesi tanpa aktivitas (dalam satuan DETIK)
# Contoh: 1800 detik = 30 menit. Silakan sesuaikan dengan kebutuhan Mas Adi
SESSION_COOKIE_AGE = 1800  

# Setiap kali operator melakukan aktivitas (klik menu, simpan kuesioner), 
# waktu tunggu (countdown) 30 menit di atas akan otomatis direset kembali dari nol.
SESSION_SAVE_EVERY_REQUEST = True

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'https://evaluasi.msafok.my.id',
]