# Generated by Django 5.2.14 on 2026-06-05 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndikatorEvaluasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_indikator', models.IntegerField(verbose_name='Nomor Indikator')),
                ('nama_indikator', models.CharField(max_length=255, verbose_name='Nama Indikator')),
                ('penjelasan', models.TextField(blank=True, null=True, verbose_name='Penjelasan / Definisi')),
                ('tipe_penilaian', models.CharField(choices=[('BERJENJANG', 'Pilihan Berjenjang / Level (e.g., Level 1-5)'), ('BINER', 'Ya / Tidak'), ('INPUT_ANGKA', 'Input Angka / Persentase Manual')], default='BERJENJANG', max_length=20, verbose_name='Tipe Penilaian')),
            ],
            options={
                'verbose_name_plural': '3. Bank Indikator Utama',
            },
        ),
        migrations.CreateModel(
            name='OPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_opd', models.CharField(help_text='Contoh: Dinas Komunikasi dan Informatika', max_length=150, unique=True, verbose_name='Nama OPD')),
                ('kode_opd', models.CharField(help_text='Contoh: DISKOMINFO', max_length=50, unique=True, verbose_name='Kode OPD')),
                ('singkatan', models.CharField(blank=True, help_text='Contoh: Kominfo', max_length=30, null=True, verbose_name='Singkatan')),
            ],
            options={
                'verbose_name': 'Master OPD',
                'verbose_name_plural': 'Master OPD',
                'ordering': ['nama_opd'],
            },
        ),
        migrations.CreateModel(
            name='BobotIndikatorPeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bobot_nilai', models.DecimalField(decimal_places=2, max_digits=5)),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluasi.indikatorevaluasi')),
            ],
            options={
                'verbose_name': 'Pengaturan Bobot & Hak Akses Indikator',
                'verbose_name_plural': 'Pengaturan Bobot & Hak Akses Indikator',
            },
        ),
        migrations.CreateModel(
            name='JenisIndeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_indeks', models.CharField(max_length=20, unique=True, verbose_name='Kode Indeks (e.g., SPBE-2025, SPBE-2026)')),
                ('nama_indeks', models.CharField(max_length=255, verbose_name='Nama Panjang Indeks')),
                ('tahun_berlaku', models.IntegerField(default=2026, verbose_name='Tahun Berlaku')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan / Dasar Hukum')),
                ('indikator_diujikan', models.ManyToManyField(blank=True, related_name='indeks_terkait', through='evaluasi.BobotIndikatorPeriode', to='evaluasi.indikatorevaluasi', verbose_name='Daftar Indikator yang Diujikan pada Periode Ini')),
            ],
            options={
                'verbose_name_plural': '1. Master Jenis Indeks (Periode)',
            },
        ),
        migrations.AddField(
            model_name='bobotindikatorperiode',
            name='jenis_indeks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluasi.jenisindeks'),
        ),
        migrations.CreateModel(
            name='KomponenEvaluasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('DOMAIN', 'Domain / Rumpun Atas'), ('ASPEK', 'Aspek Penilaian'), ('LAINNYA', 'Tipe Kustom Lainnya')], default='ASPEK', max_length=20, verbose_name='Tipe Struktur')),
                ('kode_komponen', models.CharField(max_length=10, verbose_name='Kode (e.g., D1, A1, L1)')),
                ('nama_komponen', models.CharField(max_length=255, verbose_name='Nama Komponen')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_komponen', to='evaluasi.komponenevaluasi', verbose_name='Induk Komponen (Parent)')),
            ],
            options={
                'verbose_name_plural': '2. Bank Struktur Komponen',
            },
        ),
        migrations.AddField(
            model_name='indikatorevaluasi',
            name='komponen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indikator_list', to='evaluasi.komponenevaluasi', verbose_name='Struktur Komponen Terdalam'),
        ),
        migrations.AddField(
            model_name='bobotindikatorperiode',
            name='opd_penanggung_jawab',
            field=models.ManyToManyField(blank=True, help_text='Kosongkan jika indikator ini bersifat UMUM untuk semua OPD pada periode ini.', related_name='bobot_indikator_assigned', to='evaluasi.opd'),
        ),
        migrations.CreateModel(
            name='PilihanJawabanIndikator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_angka', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nilai (Angka/Skor)')),
                ('label_level', models.CharField(max_length=50, verbose_name='Label (e.g., Level 1, Ya, Kurang)')),
                ('narasi_kriteria', models.TextField(verbose_name='Narasi Kriteria / Penjelasan Detail Jawaban')),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihan_jawaban', to='evaluasi.indikatorevaluasi', verbose_name='Indikator')),
            ],
            options={
                'verbose_name_plural': '4. Bank Pilihan Jawaban Indikator',
                'ordering': ['nilai_angka'],
            },
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150, verbose_name='Nama Lengkap & Gelar')),
                ('nip', models.CharField(max_length=50, unique=True, verbose_name='NIP')),
                ('no_hp', models.CharField(max_length=20, verbose_name='No HP')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('jabatan', models.CharField(max_length=100, verbose_name='Jabatan')),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True, verbose_name='Jenis Kelamin')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('SUPERVISOR', 'Supervisor (Tim Verifikator)'), ('OPERATOR', 'Operator (Perwakilan OPD)')], default='OPERATOR', max_length=20, verbose_name='Hak Akses / Role')),
                ('salah_login_count', models.IntegerField(default=0, verbose_name='Jumlah Salah Login')),
                ('is_active_sw', models.BooleanField(default=True, verbose_name='Akun Aktif (Software)')),
                ('last_session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='ID Sesi Terakhir')),
                ('opd', models.ForeignKey(blank=True, help_text='Pilih Instansi/OPD tempat pegawai ini bertugas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai_opd', to='evaluasi.opd', verbose_name='Instansi/OPD')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='indikatorevaluasi',
            unique_together={('komponen', 'nomor_indikator')},
        ),
        migrations.AlterUniqueTogether(
            name='bobotindikatorperiode',
            unique_together={('jenis_indeks', 'indikator')},
        ),
        migrations.CreateModel(
            name='TransaksiEvaluasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_bukti_dukung', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Bukti Dukung (Drive/Cloud)')),
                ('catatan_opd', models.TextField(blank=True, null=True, verbose_name='Penjelasan/Catatan dari OPD')),
                ('catatan_supervisor', models.TextField(blank=True, null=True, verbose_name='Catatan/Rekomendasi Supervisor')),
                ('status', models.CharField(choices=[('DRAF', 'Draf (Belum Dikirim)'), ('SUBMITTED', 'Diajukan ke Supervisor'), ('VERIFIED', 'Selesai Diverifikasi')], default='DRAF', max_length=20, verbose_name='Status Dokumen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indeks_aktif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_indeks_list', to='evaluasi.jenisindeks', verbose_name='Periode Evaluasi')),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_list', to='evaluasi.indikatorevaluasi', verbose_name='Indikator')),
                ('opd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasil_evaluasi_opd', to='evaluasi.opd', verbose_name='Instansi / OPD Pengisi')),
                ('pilihan_mandiri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilihan_opd', to='evaluasi.pilihanjawabanindikator', verbose_name='Jawaban Mandiri')),
                ('pilihan_verifikasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilihan_verifikator', to='evaluasi.pilihanjawabanindikator', verbose_name='Jawaban Hasil Verifikasi')),
                ('user_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifier_transaksi', to=settings.AUTH_USER_MODEL, verbose_name='Operator Pengubah Terakhir')),
            ],
            options={
                'verbose_name_plural': 'Transaksi Evaluasi Mandiri',
                'unique_together': {('opd', 'indeks_aktif', 'indikator')},
            },
        ),
    ]
