# Generated by Django 5.2.14 on 2026-06-05 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluasi', '0002_buat_tabel_transaksi_baru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksievaluasi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaksievaluasi',
            name='opd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasil_evaluasi_opd', to='evaluasi.opd', verbose_name='Instansi / OPD Pengisi'),
        ),
    ]
