# Generated by Django 6.0.6 on 2026-06-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluasi', '0003_alter_transaksievaluasi_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='indeks_akses',
            field=models.ManyToManyField(blank=True, help_text='Pilih jenis indeks yang boleh diisi (Operator) atau disupervisi (Supervisor) oleh user ini. Kosongkan jika Superadmin memiliki semua akses.', related_name='user_diizinkan', to='evaluasi.jenisindeks', verbose_name='Akses Jenis Indeks'),
        ),
    ]
