# Generated by Django 6.0.6 on 2026-06-12 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluasi', '0004_profileuser_indeks_akses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(choices=[('LOGIN', 'Login ke Sistem'), ('LOGOUT', 'Logout dari Sistem'), ('SIMPAN_JAWABAN', 'Simpan / Update Jawaban Kuesioner'), ('HAPUS_JAWABAN', 'Hapus Jawaban Kuesioner'), ('SUBMIT', 'Submit Kuesioner ke Supervisor'), ('APPROVE', 'Approve / Verifikasi Jawaban'), ('REJECT', 'Tolak / Kembalikan ke Draf'), ('GANTI_PASSWORD', 'Ganti Password')], max_length=30, verbose_name='Jenis Aktivitas')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Detail Aktivitas')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indeks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='evaluasi.jenisindeks', verbose_name='Indeks Terkait')),
                ('opd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='evaluasi.opd', verbose_name='OPD Terkait')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
