# Generated by Django 6.0.6 on 2026-06-15 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluasi', '0005_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='komponenevaluasi',
            options={'ordering': ['kode_komponen'], 'verbose_name_plural': '2. Bank Struktur Komponen'},
        ),
        migrations.AlterUniqueTogether(
            name='transaksievaluasi',
            unique_together={('indeks_aktif', 'indikator')},
        ),
        migrations.AddField(
            model_name='transaksievaluasi',
            name='opd_pengisi_terakhir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_diisi', to='evaluasi.opd', verbose_name='OPD Pengisi Terakhir'),
        ),
        migrations.AlterField(
            model_name='transaksievaluasi',
            name='catatan_opd',
            field=models.TextField(blank=True, null=True, verbose_name='Penjelasan/Catatan OPD'),
        ),
        migrations.AlterField(
            model_name='transaksievaluasi',
            name='pilihan_mandiri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilihan_kolektif', to='evaluasi.pilihanjawabanindikator', verbose_name='Jawaban Kolektif'),
        ),
        migrations.RemoveField(
            model_name='transaksievaluasi',
            name='opd',
        ),
    ]
