# Generated by Django 6.0.6 on 2026-06-17 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluasi', '0006_alter_komponenevaluasi_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('APPROVE', 'Indikator Disetujui'), ('REJECT', 'Indikator Dikembalikan')], max_length=20, verbose_name='Tipe Notifikasi')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul Notifikasi')),
                ('pesan', models.TextField(verbose_name='Isi Pesan')),
                ('sudah_dibaca', models.BooleanField(default=False, verbose_name='Sudah Dibaca')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indeks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi_list', to='evaluasi.jenisindeks', verbose_name='Indeks Terkait')),
                ('penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi_masuk', to=settings.AUTH_USER_MODEL, verbose_name='Penerima')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi_list', to='evaluasi.transaksievaluasi', verbose_name='Transaksi Terkait')),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-created_at'],
            },
        ),
    ]
